### ISSUE TITLE
Get value of current preference

### ISSUE THREAD

**Issue by brokeniceinteractive** [codevscolor/MaterialPreference#10]
Hi, how can i get the current value of row from: 

` public void onPreferenceSettingsChanged(SharedPreferences sharedPreferences, String name) `

Example in a switch i want to know if it's true or false, ecc.

**Comment by codevscolor** [comment]
you can get this value from sharedPreferences using "key" name 

e.g. sharedPreferences.getBoolean("Checkbox_key",false))
