### ISSUE TITLE
How to disable a checkbox programmatically ? 

### ISSUE THREAD

**Issue by crockkaw** [codevscolor/MaterialPreference#13]
I found sth like this: 
`getPreferenceScreen().findPreference("Checkbox_true").setEnabled(false);`
It's not working, how can I use it ? 
Is there other better option to do this ?

**Comment by codevscolor** [comment]
You cannot use enabled/disabled from application. but if you want to use it on your project then :
1. Import this library project directly ( don't use the gradle dependency )
2. Inside MaterialPreferenceFragment.java, write your own logic after `addPreferencesFromResource` is called .

Please let me know your app logic ( when you want to disable/enable in runtime) .

**Comment by crockkaw** [comment]
I did like you said and it works. 

Thanks for the quick help :)

**Comment by codevscolor** [comment]
welcome :)
