### ISSUE TITLE
Toast not show after adding Preference

### ISSUE THREAD

**Issue by jp1017** [codevscolor/MaterialPreference#6]
I add this in `Category Two`:

```
        <android.support.v7.preference.Preference
            android:title="inst"
            android:key="inst"
        />
```

it doesn't show theToast when I reinstall this apk.

Any help for me?

**Comment by codevscolor** [comment]
are you using the latest version ? Please try with the demp application.

**Comment by jp1017** [comment]
Yes, the latest version.

**Comment by codevscolor** [comment]
Sorry for replying late. But I was not able to reproduce this issue. Please reopen it again if reproduced.
